### ISSUE TITLE
Support non-buildable projects/packages

### ISSUE THREAD

**Issue by shaharkazaz** [lemonade-hq/traf#1]
Hi! 
Thanks for the tool 🙂 
I recommend that you open the discussion section for Q&A.

I have an nx workspace with buildable apps that consume non-buildable packages.
Looking at the [code](https://github.com/lemonade-hq/traf/blob/b80623878e7a67dbee4a9440029884bf233de5b6/libs/nx/src/cli.ts#L30) these packages are filtered out which causes the command to not work properly.
The tsconfig path can be easily resolved once you have the project path.

**Comment by EladBezalel** [comment]
@shaharkazaz hey! 

Thanks for the suggestion, opened up discussions :)

You're right, this tool looks for build script in order to find the relevant `tsconfig` file.
How would you suggest it to work otherwise? it's important to get the `tsconfig` without the tests files so it won't do extra calculations and possibly end in infinite loop.

In your usecase, do you have any other indication to the `tsconfig` in the `project.json` file?

**Comment by shaharkazaz** [comment]
@EladBezalel The fact that it's an nx-oriented plugin makes it easier to resolve the `tsconfig` since the workspace structure should be known.

You should have the following lib structure:
```
|-- packages
| -- my-package
|  |-- project.json
|  |-- tsconfig.json
|  |-- tsconfig.lib.json
|  |-- .eslintrc.json
|  |-- tsconfig.spec.json
|  |-- jest.config.ts
|  |-- src
```

Given the fact that we have the project file location, as a start I would search for the config (`tsconfig.lib.json`) in the same directory.
In case there will be more complicated use cases we can always extract the package name and perform a search from that entry point.

But I think that assuming that this is the project's structure is ok.

**Comment by EladBezalel** [comment]
Yeah, it's possible to fallback to `tsconfig.lib.json` incase we couldn't find build script for a given project, should be fairly easy.

**Comment by EladBezalel** [comment]
Actually, looking at some code examples, in `apps` in nx, the default tsconfig is `tsconfig.src.json`, also saw one usecase where it's just `tsconfig.json`
I feel like it's not deterministic enough,
How about adding a `.trafconfig` file with overrides?

**Comment by shaharkazaz** [comment]
@EladBezalel Have you encountered a non-buildable app? 🤔 

I wouldn't also assume that if something is missing in the build config it's a library, you have the project file and it has a `projectType` property from which we can understand the expected `tsconfig` convention.
You can also prioritize the config search: `tsconfig.{lib, app, src}.ts` -> `tsconfig.ts`

IMHO you should keep this package at the minimum config, like as I said, working with NX does give you a convention to rely on, if many users will have customized their workspace they will report and you can always add a config file, but to the average user, the package should support OOTB.

**Comment by yharaskrik** [comment]
> Actually, looking at some code examples, in `apps` in nx, the default tsconfig is `tsconfig.src.json`, also saw one usecase where it's just `tsconfig.json`
> I feel like it's not deterministic enough,
> How about adding a `.trafconfig` file with overrides?

I have never encountered tsconfig.src.json in my years of Nx. It's always tsconfig.json for the main one. Then .lib. for src files, .spec. for test files that both extend tsconfig.json

**Comment by EladBezalel** [comment]
@yharaskrik Thanks for the feedback, actually you're right, i've tried to create a new nx project and no more tsconfig.src.json :)

Gonna fix my PR

**Comment by shaharkazaz** [comment]
@EladBezalel LMK when the new version is out 🙌

**Comment by skazaz-utila** [comment]
@EladBezalel Works like a charm 👌

**Comment by shaharkazaz** [comment]
@EladBezalel Works like a charm 👌
