### ISSUE TITLE
Unable to resolve affected projects in Nx workspace (undefined `project.sourceRoot` because `project` is a string) 

### ISSUE THREAD

**Issue by arkus7** [lemonade-hq/traf#17]
Hi,

Thanks for building this tool. I wanted to test this on my monorepo to see how it works. Unfortunately, I can't run the base command `npx @traf/nx@latest affected` as there is some issue with finding the project root.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at join (node:path:1172:7)
    at file:///Users/arkus/Projects/<project-name>/node_modules/@traf/nx/cli.js:237:27
    at Array.map (<anonymous>)
    at getNxTrueAffectedProjects (file:///Users/arkus/Projects/<project-name>/node_modules/@traf/nx/cli.js:233:19)
    at async affectedAction (file:///Users/arkus/Projects/<project-name>/node_modules/@traf/nx/cli.js:271:20)
    at async Object.handler (file:///Users/arkus/Projects/<project-name>/node_modules/@traf/nx/cli.js:361:5)
 ```
 
 So it seems the issue is in this line 
 
 https://github.com/lemonade-hq/traf/blob/f49cdec839d7f5d7480e3975b597cae25a07d0ea/libs/nx/src/nx.ts#L88

It seems like in my project the types are a bit different than `traf` expects them to be.

https://github.com/lemonade-hq/traf/blob/f49cdec839d7f5d7480e3975b597cae25a07d0ea/libs/nx/src/nx.ts#L7-L19

When I run the CLI command on my project, the `project` (which is expected to be of `NxProject` type) is just a string with the path to the project directory.

If I understood it correctly, the `projects` come from the `workspace.json` file, which is (at least for me) a map of `{ [projectName]: [pathToTheProject] }`.

Is there something I'm missing in my setup to allow this tool to work? I updated the `nx` version to the `16.2.2` as it's here in `package.json` dependencies, but no luck.
```[tasklist]
### Tasks
- [ ] nx: support `workspace.json` without project configuration (just paths to the projects)
```

**Comment by arkus7** [comment]
Hi, thanks for the prompt response!

As you mentioned, I missed some things when upgrading nx. I applied migrations to the latest versions and I'll try again when I see everything works correctly.

I did have the `sourceRoot` properties in the `project.json` files, but I think the presence of `workspace.json` bamboozled `traf` to look for it there.

As mentioned [here on the `workspace.json` docs](https://nx.dev/deprecated/workspace-json), this file is deprecated and no longer should be used. There is even a one-liner to fix this but I haven't tried it, as I went for the `nx migrate` command instead (which removed the `workspace.json` file).

It even says

> If every project is listed as a string, instead of an object with project configuration properties, then it is safe to delete the workspace.json file.

which was the case for me from the start.

When it comes to solutions on how to fix that, I imagine traf could:
- check the version of nx installed on the project, if it's <15, alert users to migrate to nx >=15 (not technically sure how difficult that is)
- if the `workspace.json` is present, check if the values are strings
  - if so, skip the `workspace.json` file and look for `project.json` files
  - otherwise, display a warning for the user that this file is deprecated, link to some Nx documentation, mention that it might not work correctly and try to carry on
  
Let me know what do you think about that @EladBezalel

**Comment by EladBezalel** [comment]
@arkus7 love that! sounds like the right solution, are you willing to look into it? 🙏

**Comment by arkus7** [comment]
Sure, I should be able take a look into that this weekend.
Now when I think of it, I don't think the version checking is necessary, the check for presence of workspace.json file should be enough.

What are your strategies for testing such cases? Would I need to create some nx workspace for in tests to make sure it works correctly?

**Comment by EladBezalel** [comment]
Look at the `__fixtures__` folder,
I won't go full nx repo, just what's necessary for the test

**Comment by arkus7** [comment]
@EladBezalel I would appreciate some feedback in the #18 ;)

**Comment by arkus7** [comment]
Just FYI @EladBezalel, it seems that there was [some issue with releasing this update](https://github.com/lemonade-hq/traf/actions/runs/5806443624/job/15739345102).

**Comment by EladBezalel** [comment]
Yeah the release process is broken, I need to manually deploy it, will do in a bit
