### ISSUE TITLE
feature request: include library root folder changes as affected

### ISSUE THREAD

**Issue by ShayDavidson** [lemonade-hq/traf#6]
Both in NX and Traf right now, if I change for example the `package.json` of a library (which can affect its build) - it doesn't end up in the "affected" list, hence I need to manually change something silly in the code (a comment, ordering) in order to trigger a build.

Can we somehow add that these kind of changes do count as "affected"? it doesn't need to add into the affected results the libraries that depend on my change, but only the library itself

**Comment by raz-ezra-lmnd** [comment]
@ShayDavidson @EladBezalel 

2 questions -
- Do we want to support `package.json` only, or - 
	- Have a closed set of files (like `rollup/webpack.config` or other things affecting different scenarios
	- Add a flag for file to `include`
		- Useful when you are in different contexts (for example testing - you would want changes to jest.config to take action, while in build, you don’t care about it)
- Unrelated - I noticed we are adding all implicitDependencies of all packages, even if none of them changed. Is it intentional? I believe we should build implicit deps of affected packages only, no?

**Comment by raz-ezra-lmnd** [comment]
PR to add support for `includeFiles`:
https://github.com/lemonade-hq/traf/pull/9
